# Generated by Django 5.2.8 on 2025-11-23 10:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Regions',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sensor_id', models.CharField(max_length=50, unique=True)),
                ('sensor_type', models.CharField(choices=[('temperature', 'Temperature'), ('oil_level', 'Oil Level'), ('pressure', 'Pressure'), ('current', 'Current'), ('voltage', 'Voltage'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Sensors',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Depot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depots', to='api.region')),
            ],
            options={
                'verbose_name_plural': 'Depots',
                'ordering': ['name'],
                'unique_together': {('name', 'region')},
            },
        ),
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_alert', models.BooleanField(default=False, help_text='Indicates if this reading triggered an alert')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='api.sensor')),
            ],
            options={
                'verbose_name_plural': 'Sensor Readings',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Transformer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('transformer_id', models.CharField(max_length=50, unique=True)),
                ('installation_date', models.DateField(blank=True, null=True)),
                ('capacity', models.DecimalField(decimal_places=2, help_text='Transformer capacity in MVA', max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('depot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transformers', to='api.depot')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transformers', to='api.region')),
            ],
            options={
                'verbose_name_plural': 'Transformers',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='sensor',
            name='transformer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='api.transformer'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_national_level', models.BooleanField(default=False, help_text='User can access all regions, depots, and transformers')),
                ('is_region_level', models.BooleanField(default=False, help_text='User can access all transformers in their assigned region')),
                ('is_depot_level', models.BooleanField(default=False, help_text='User can access only transformers in their assigned depot')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('depot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='api.depot')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='api.region')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Profiles',
                'ordering': ['user__username'],
            },
        ),
    ]
