# Generated by Django 5.2.8 on 2025-11-24 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='sensor_type',
            field=models.CharField(choices=[('temperature', 'Temperature'), ('oil_level', 'Oil Level'), ('pressure', 'Pressure'), ('current', 'Current'), ('voltage', 'Voltage'), ('humidity', 'Humidity'), ('contact', 'Contact'), ('motion', 'Motion'), ('video', 'Video'), ('other', 'Other')], max_length=20),
        ),
    ]
