# Generated by Django 5.2.8 on 2025-11-24 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_device_devicesensormap'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceUplink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port', models.IntegerField()),
                ('topic', models.CharField(max_length=200)),
                ('raw', models.JSONField(default=dict)),
                ('value', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('ts_device', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uplinks', to='api.device')),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
    ]
