# Generated by Django 5.2.8 on 2025-11-25 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_deviceuplink'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='codec',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
