# Generated by Django 5.2.8 on 2025-11-25 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_device_codec'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='dev_eui',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='sensor',
            name='fport',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sensor',
            name='meta',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='sensorreading',
            name='decoded',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sensorreading',
            name='raw_payload',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='sensorreading',
            name='received_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sensorreading',
            name='topic',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sensorreading',
            name='is_alert',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sensorreading',
            name='sensor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='api.sensor'),
        ),
        migrations.AlterField(
            model_name='sensorreading',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='sensor',
            unique_together={('dev_eui', 'fport')},
        ),
        migrations.AddIndex(
            model_name='sensorreading',
            index=models.Index(fields=['sensor', 'received_at'], name='api_sensorr_sensor__8d2112_idx'),
        ),
        migrations.AddIndex(
            model_name='sensorreading',
            index=models.Index(fields=['received_at'], name='api_sensorr_receive_eebfde_idx'),
        ),
    ]
