# Generated by Django 5.2.8 on 2025-11-25 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_sensor_dev_eui_sensor_fport_sensor_meta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='sensor_type',
            field=models.CharField(choices=[('temperature', 'Temperature'), ('current', 'Current'), ('voltage', 'Voltage'), ('humidity', 'Humidity'), ('contact', 'Contact'), ('motion', 'Motion'), ('tilt', 'Tilt'), ('video', 'Video'), ('oil_level', 'Oil Level'), ('other', 'Other')], max_length=20),
        ),
    ]
